#!/usr/bin/env python3
"""
Mrk Training Script (following LAN_ori architecture)

Trains 4 binary rankers (shared backbone) for neighbor pruning.
- Q: GIN with degree one-hot features
- G, G': pre-computed Node2Vec embeddings
- MLP classifier with BatchNorm + Dropout

Training data: JSON file generated by mrk_data_gen.py
Model: MrkModel from mrk_model.py
"""

import os
import json
import math
import random
import logging
import pickle
import time
from functools import partial

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim.lr_scheduler import StepLR
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import dgl

from mrk_model import MrkModel, nx_to_dgl

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INDEX_FILE = os.path.join(SCRIPT_DIR, 'indexes', 'AIDS_LAN_index.pkl')
DATA_DIR = os.path.join(SCRIPT_DIR, 'training_data')
MODEL_DIR = os.path.join(SCRIPT_DIR, 'models', 'mrk')
EMB_DIR = os.path.join(SCRIPT_DIR, 'emb')


def load_training_data():
    data_file = os.path.join(DATA_DIR, 'mrk_train_data.json')
    logger.info(f"Loading training data from {data_file}...")
    with open(data_file) as f:
        data = json.load(f)
    logger.info(f"  {data['num_samples']} samples, gamma*={data['gamma_star']}, y={data['y']}")
    return data


def load_graph_map():
    logger.info("Loading graph data from PG index...")
    with open(INDEX_FILE, 'rb') as f:
        index_data = pickle.load(f)
    graph_map = index_data['graph_id_to_original']
    logger.info(f"  {len(graph_map)} graphs loaded")
    return graph_map


def load_node2vec_embeddings(emb_dim=512):
    pkl_path = os.path.join(EMB_DIR, f'aids{emb_dim}_graph_emb.pkl')
    logger.info(f"Loading Node2Vec embeddings from {pkl_path}...")
    with open(pkl_path, 'rb') as f:
        emb_map = pickle.load(f)
    # Ensure all values are torch.Tensor (pkl may contain np.ndarray)
    import torch
    for k, v in emb_map.items():
        if not isinstance(v, torch.Tensor):
            emb_map[k] = torch.from_numpy(v)
    logger.info(f"  {len(emb_map)} graph embeddings loaded (dim={emb_dim})")
    return emb_map


def prepare_labels(neighbor_geds, num_rankers=4, y=20):
    """Create labels for each ranker given sorted neighbor GEDs."""
    k = len(neighbor_geds)
    labels = {}
    for i in range(num_rankers):
        threshold_count = max(1, math.ceil(k * (i + 1) * y / 100))
        threshold_count = min(threshold_count, k)
        label = [1 if j < threshold_count else 0 for j in range(k)]
        labels[i] = label
    return labels


class MrkDataset(Dataset):
    """Dataset for Mrk training."""

    def __init__(self, instances):
        """
        Args:
            instances: list of (q_dgl, g_emb, neigh_embs, labels_dict)
        """
        self.instances = instances

    def __len__(self):
        return len(self.instances)

    def __getitem__(self, idx):
        return self.instances[idx]


def collate_fn(samples, num_rankers=4):
    """
    Collate function for DataLoader.

    Returns:
        q_batch: batched DGL graph
        g_embs: [batch_size, emb_dim]
        neigh_embs: [total_neighbors, emb_dim]
        neigh_counts: [batch_size] int tensor
        all_targets: [total_neighbors, num_rankers]
    """
    q_dgls = []
    g_embs = []
    neigh_embs_list = []
    neigh_counts = []
    all_targets = []

    for q_dgl, g_emb, neigh_embs, labels in samples:
        q_dgls.append(q_dgl)
        g_embs.append(g_emb)
        neigh_embs_list.append(neigh_embs)
        k = neigh_embs.size(0)
        neigh_counts.append(k)

        # Build target tensor [k, num_rankers]
        target = torch.zeros(k, num_rankers)
        for r in range(num_rankers):
            target[:, r] = torch.tensor(labels[r], dtype=torch.float32)
        all_targets.append(target)

    q_batch = dgl.batch(q_dgls)
    g_embs = torch.stack(g_embs)
    neigh_embs = torch.cat(neigh_embs_list, dim=0)
    neigh_counts = torch.tensor(neigh_counts, dtype=torch.long)
    all_targets = torch.cat(all_targets, dim=0)

    return q_batch, g_embs, neigh_embs, neigh_counts, all_targets


def weighted_bce(output, target, weights=(1.0, 1.0)):
    """Weighted BCE loss.
    weights[0]=1.0 for negative class, weights[1]=1.0 for positive class (standard BCE)."""
    output = torch.clamp(output, min=1e-6, max=1 - 1e-6)
    loss = weights[1] * (target * torch.log(output)) + \
           weights[0] * ((1 - target) * torch.log(1 - output))
    return torch.neg(torch.mean(loss))


def compute_metrics(model, dataloader, num_rankers):
    """Compute loss, accuracy, precision, recall on a dataset."""
    model.eval()
    total_loss = 0.0
    num_batches = 0
    # Per-ranker counters
    tp = [0] * num_rankers
    fp = [0] * num_rankers
    fn = [0] * num_rankers
    correct = [0] * num_rankers
    total = [0] * num_rankers

    with torch.no_grad():
        for q_batch, g_embs, neigh_embs, neigh_counts, targets in dataloader:
            logits = model.forward_batch(q_batch, g_embs, neigh_embs, neigh_counts)
            preds = torch.sigmoid(logits)

            loss = torch.tensor(0.0)
            for r in range(num_rankers):
                loss = loss + weighted_bce(preds[:, r], targets[:, r])
            loss = loss / num_rankers
            total_loss += loss.item()
            num_batches += 1

            binary_preds = (preds > 0.5).float()
            for r in range(num_rankers):
                t = targets[:, r]
                p = binary_preds[:, r]
                tp[r] += ((p == 1) & (t == 1)).sum().item()
                fp[r] += ((p == 1) & (t == 0)).sum().item()
                fn[r] += ((p == 0) & (t == 1)).sum().item()
                correct[r] += (p == t).sum().item()
                total[r] += t.numel()

    avg_loss = total_loss / max(num_batches, 1)
    metrics = {'loss': avg_loss}

    acc_list, prec_list, rec_list = [], [], []
    for r in range(num_rankers):
        acc = correct[r] / max(total[r], 1)
        prec = tp[r] / max(tp[r] + fp[r], 1)
        rec = tp[r] / max(tp[r] + fn[r], 1)
        acc_list.append(acc)
        prec_list.append(prec)
        rec_list.append(rec)

    metrics['acc'] = sum(acc_list) / num_rankers
    metrics['prec'] = sum(prec_list) / num_rankers
    metrics['rec'] = sum(rec_list) / num_rankers

    return metrics


def train_mrk(num_epochs=1000, lr=0.005, lr_decay=0.95, lr_step=2,
              emb_dim=512, num_layers=2, batch_size=1000,
              save_every=100, seed=42, val_ratio=0.2):
    """Train the Mrk model."""
    random.seed(seed)
    torch.manual_seed(seed)
    os.makedirs(MODEL_DIR, exist_ok=True)

    # Load data
    train_data = load_training_data()
    graph_map = load_graph_map()
    emb_map = load_node2vec_embeddings(emb_dim)
    samples = train_data['samples']
    num_rankers = train_data.get('num_rankers', 4)
    y = train_data.get('y', 20)

    logger.info(f"Training config: epochs={num_epochs}, lr={lr}, "
                f"emb_dim={emb_dim}, layers={num_layers}, batch_size={batch_size}")

    # Pre-convert all needed Q graphs to DGL (cache)
    logger.info("Pre-converting query graphs to DGL format...")
    dgl_cache = {}
    needed_qids = set(s['query_id'] for s in samples)
    for qid in needed_qids:
        if qid in graph_map and qid not in dgl_cache:
            dgl_cache[qid] = nx_to_dgl(graph_map[qid])
    logger.info(f"  Cached {len(dgl_cache)} DGL graphs")

    # Build training instances
    logger.info("Building training instances...")
    instances = []
    skipped_no_emb = 0
    for sample in samples:
        qid = sample['query_id']
        gid = sample['pg_node_id']

        if qid not in dgl_cache:
            continue
        if gid not in emb_map:
            skipped_no_emb += 1
            continue

        q_dgl = dgl_cache[qid]
        g_emb = emb_map[gid]

        # Sort neighbors by GED
        neighbors = sorted(sample['neighbors'], key=lambda x: x['ged'])

        # Filter: neighbor must have embedding
        valid_neighbors = [(n['id'], n['ged']) for n in neighbors if n['id'] in emb_map]
        if len(valid_neighbors) < 2:
            continue

        neigh_embs = torch.stack([emb_map[nid] for nid, _ in valid_neighbors])
        labels = prepare_labels(valid_neighbors, num_rankers, y)

        instances.append((q_dgl, g_emb, neigh_embs, labels))

    logger.info(f"  {len(instances)} instances ({skipped_no_emb} skipped: no embedding)")

    if len(instances) == 0:
        logger.error("No training instances! Check training data and embeddings.")
        return

    # Train/Val split
    random.shuffle(instances)
    val_size = int(len(instances) * val_ratio)
    train_instances = instances[val_size:]
    val_instances = instances[:val_size]
    logger.info(f"  Train: {len(train_instances)}, Val: {len(val_instances)}")

    # Create datasets and dataloaders
    collate = partial(collate_fn, num_rankers=num_rankers)
    train_loader = DataLoader(
        MrkDataset(train_instances),
        batch_size=batch_size, collate_fn=collate,
        shuffle=True, drop_last=False, num_workers=0
    )
    val_loader = DataLoader(
        MrkDataset(val_instances),
        batch_size=batch_size, collate_fn=collate,
        shuffle=False, drop_last=False, num_workers=0
    )

    # Create model
    model = MrkModel(
        num_rankers=num_rankers,
        emb_dim=emb_dim,
        num_layers=num_layers
    )

    total_params = sum(p.numel() for p in model.parameters())
    logger.info(f"Model parameters: {total_params:,}")

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = StepLR(optimizer, step_size=lr_step, gamma=lr_decay)

    # Training loop
    best_val_loss = float('inf')
    logger.info(f"\nStarting training for {num_epochs} epochs...")
    logger.info(f"  Train: {len(train_instances)} instances, {len(train_loader)} batches")
    logger.info(f"  Val: {len(val_instances)} instances, {len(val_loader)} batches")

    for epoch in range(num_epochs):
        model.train()
        epoch_loss = 0.0
        epoch_batches = 0
        epoch_start = time.time()

        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}", leave=False)
        for q_batch, g_embs, neigh_embs, neigh_counts, targets in pbar:
            # Forward
            logits = model.forward_batch(q_batch, g_embs, neigh_embs, neigh_counts)
            preds = torch.sigmoid(logits)  # [total_neighbors, num_rankers]

            # Loss: weighted BCE averaged over rankers
            loss = torch.tensor(0.0)
            for r in range(num_rankers):
                r_loss = weighted_bce(preds[:, r], targets[:, r])
                loss = loss + r_loss
            loss = loss / num_rankers

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            epoch_batches += 1
            pbar.set_postfix(loss=f"{epoch_loss/epoch_batches:.4f}")

        scheduler.step()
        epoch_time = time.time() - epoch_start
        train_loss = epoch_loss / max(epoch_batches, 1)

        # Compute train and val metrics
        train_m = compute_metrics(model, train_loader, num_rankers)
        val_m = compute_metrics(model, val_loader, num_rankers)

        current_lr = scheduler.get_last_lr()[0]
        logger.info(
            f"Epoch {epoch+1}/{num_epochs} ({epoch_time:.1f}s, lr={current_lr:.6f}): "
            f"train loss={train_m['loss']:.4f} acc={train_m['acc']:.3f} "
            f"prec={train_m['prec']:.3f} rec={train_m['rec']:.3f} | "
            f"val loss={val_m['loss']:.4f} acc={val_m['acc']:.3f} "
            f"prec={val_m['prec']:.3f} rec={val_m['rec']:.3f}"
        )

        # Save checkpoint
        if (epoch + 1) % save_every == 0:
            ckpt_file = os.path.join(MODEL_DIR, f'mrk_epoch_{epoch+1}.pth')
            torch.save({
                'epoch': epoch + 1,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'train_metrics': train_m,
                'val_metrics': val_m,
                'config': {
                    'num_rankers': num_rankers,
                    'emb_dim': emb_dim,
                    'num_layers': num_layers,
                }
            }, ckpt_file)
            logger.info(f"  Saved checkpoint: {ckpt_file}")

        # Save best model (by val loss)
        if val_m['loss'] < best_val_loss:
            best_val_loss = val_m['loss']
            best_file = os.path.join(MODEL_DIR, 'mrk_best.pth')
            torch.save({
                'epoch': epoch + 1,
                'model_state_dict': model.state_dict(),
                'train_metrics': train_m,
                'val_metrics': val_m,
                'config': {
                    'num_rankers': num_rankers,
                    'emb_dim': emb_dim,
                    'num_layers': num_layers,
                }
            }, best_file)

    # Save final model
    final_file = os.path.join(MODEL_DIR, 'mrk_final.pth')
    torch.save({
        'epoch': num_epochs,
        'model_state_dict': model.state_dict(),
        'train_metrics': train_m,
        'val_metrics': val_m,
        'config': {
            'num_rankers': num_rankers,
            'emb_dim': emb_dim,
            'num_layers': num_layers,
        }
    }, final_file)
    logger.info(f"\nTraining complete. Best val loss: {best_val_loss:.4f}")
    logger.info(f"Final model: {final_file}")
    logger.info(f"Best model: {os.path.join(MODEL_DIR, 'mrk_best.pth')}")


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Train Mrk model')
    parser.add_argument('--epochs', type=int, default=1000)
    parser.add_argument('--lr', type=float, default=0.005)
    parser.add_argument('--emb_dim', type=int, default=512)
    parser.add_argument('--num_layers', type=int, default=2)
    parser.add_argument('--batch_size', type=int, default=1000)
    parser.add_argument('--save_every', type=int, default=100)
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args()

    train_mrk(
        num_epochs=args.epochs,
        lr=args.lr,
        emb_dim=args.emb_dim,
        num_layers=args.num_layers,
        batch_size=args.batch_size,
        save_every=args.save_every,
        seed=args.seed
    )
